HKCR
{
	NoRemove CLSID
	{
		ForceRemove {8545BEA4-83DF-4167-B67D-5FF71162F6D4} = s 'https://github.com/datadiode/shellext'
		{
			ForceRemove 'Programmable'
			InprocServer32 = s '%MODULE%'
			{
				val ThreadingModel = s 'Apartment'
			}
		}
	}
	NoRemove *
	{
		NoRemove ShellEx
		{
			NoRemove ContextMenuHandlers
			{
				ForceRemove ShellExt = s '{8545BEA4-83DF-4167-B67D-5FF71162F6D4}'
			}
		}
	}
}

[Format source code with clang-format;de=Quellcode mit clang-format formatieren]
command="clang-format.exe" -i "<filename>" ,1
filter=*.c;*.h;*.cpp;*.hpp;*.cxx;*.hxx

[Format source code with pasfmt;de-DE=Quellcode mit pasfmt formatieren]
command="pasfmt.exe" "<filename>" ,1
filter=*.pas;*.iss

[ping 127.0.0.1 to see the progress window]
command="ping.exe" "127.0.0.1" ,3

# About this file

This is shellext's configuration file. It must be encoded in UTF-8 without BOM.
It starts with an RGS script, followed by INI sections defining the menu items.

Commands can contain placeholders for runtime-determined paths:
- `<filename>`  
  Complete path to selected file.
- `<basename>`  
  Path to selected file with filename extension stripped off.
- `<destfolder>`  
  Path to a user-selected destination folder.

The comma-separated number at the end of each command line determines how many
instances of a command are allowed to run in parallel. A negative number adds
to the number of available CPU cores. The comma must be preceded by a space to
prevent accidental merging with the preceding command line argument.
Names of or paths to executable files must be enclosed in quotation marks _iff_
they refer to locations outside the folder hosting the `shellext.dll`.

# About shellext.dll
Interfaces with Windows Explorer to add the above-defined context menu commands.  
Origin: https://github.com/datadiode/shellext  
SPDX-License-Identifier: WTFPL

# About shellext.png
Copy of `ballon.png` as contained in `fatcow-hosting-icons-3.9.2.zip`.  
Origin: https://github.com/TomasHubelbauer/fatcow-icons  
SPDX-License-Identifier: CC-BY-3.0-US
